name: Release Game Executable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller
      - name: Build executable
        run: pyinstaller --onefile --windowed --add-data "cartas;cartas" --add-data "audio;audio" --add-data "archivos;archivos" --name Truco-Argentino-Windows main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Truco-Argentino-Windows
          path: dist/Truco-Argentino-Windows.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libpulse-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame pyinstaller
      - name: Build executable
        run: pyinstaller --onefile --windowed --add-data "cartas:cartas" --add-data "audio:audio" --add-data "archivos:archivos" --name Truco-Argentino-Linux main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Truco-Argentino-Linux
          path: dist/Truco-Argentino-Linux

  release:
    name: Create GitHub Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets/
      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-assets/Truco-Argentino-Windows/Truco-Argentino-Windows.exe
            release-assets/Truco-Argentino-Linux/Truco-Argentino-Linux
