name: Compilar para Windows

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: 4. Compilar el juego
        run: |
          python -m PyInstaller --onefile --windowed --name "JuegoTruco" --icon "cartas/1-de-espada.ico" --add-data "cartas;cartas" --add-data "audio;audio" --add-data "archivos;archivos" main.py
      
      - name: 5. Empaquetar el ejecutable
        run: Compress-Archive -Path dist/JuegoTruco.exe -DestinationPath JuegoTruco-windows.zip
      
      - name: 6. Subir el archivo a la Release
        uses: softprops/action-gh-release@v1
        with:
          files: JuegoTruco-windows.zip
